[[redirects]]
	from = "https://iflix-studio-develop.netlify.app/graphql"
	to = "https://iflix-backend.herokuapp.com/graphql"
	status = 200
	force = true
	query = {path = ":path"} # COMMENT: apply this rule for /old-path?path=example

[[redirects]]
	from = "https://iflix-studio-develop.netlify.app/*"
	to = "/index.html"
	status = 200
	force = true