import {
  CloudUploadOutlined,
  FacebookFilled,
  InstagramOutlined,
  LeftOutlined,
  RightOutlined,
  StarFilled,
  StarTwoTone,
  TwitterOutlined,
  VideoCameraFilled,
  StarOutlined,
  EditOutlined,
  DeleteOutlined,
  DownOutlined,
  LogoutOutlined,
} from "@ant-design/icons";

export {
  DownOutlined,
  EditOutlined,
  DeleteOutlined,
  CloudUploadOutlined,
  FacebookFilled,
  InstagramOutlined,
  LeftOutlined,
  RightOutlined,
  StarFilled,
  StarOutlined,
  StarTwoTone,
  TwitterOutlined,
  VideoCameraFilled,
  LogoutOutlined,
};
